name: Scheduler
version: latest
category: Framework
description: Tusimple scheduler plugin for Rancher.
projectURL: https://github.com/TuSimple/scheduler
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
